-- Ejecutar una sola vez en Supabase > SQL Editor

create table if not exists public.hipotesis (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  grupo text not null,
  integrantes text,
  hipotesis text not null,
  elemento integer not null default 0 check (elemento between 0 and 3),
  propiedad integer not null default 0 check (propiedad between 0 and 3),
  causalidad integer not null default 0 check (causalidad between 0 and 3),
  proceso integer not null default 0 check (proceso between 0 and 3),
  efecto integer not null default 0 check (efecto between 0 and 3),
  prueba integer not null default 0 check (prueba between 0 and 3),
  total integer not null default 0 check (total between 0 and 18),
  fortaleza text,
  ajuste text
);

alter table public.hipotesis enable row level security;

create policy "permitir lectura publica"
on public.hipotesis for select
to anon
using (true);

create policy "permitir insercion publica"
on public.hipotesis for insert
to anon
with check (true);
